remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: My Notes
description: Just for notes
url: https://jimmyhuydev.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /notes/      # place folder name if the site is served in a subfolder
navigation:
    - text: Blogs
    internal: true
    url: ./_posts
